name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: inferno_fs_patcher
          path: build/inferno_fs_patcher
